baseURL = "https://brysonl.github.io/personal-site/"
languageCode = "en-US"
title = "bryson lockett"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "G-1T332YZ9J2"
theme = "hugo-sustain"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    style = 'monokai'
    lineNos = true
    lineNumbersInTable = false



[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "img/profile.png"
  author = "Bryson Lockett"
  description = "Bryson Lockett's personal website including his blog, projects, and resume."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "brysonl"
  Email         = "bryson@lockett.us"
  LinkedIn      = "bryson-lockett"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"
